### ISSUE TITLE
Wrong number of seconds in day?

### ISSUE THREAD

**Issue by ben-strasser** [GVeitBatz/KaTCH#1]
search_graph.h line number 54 and order_edge_data.h line number 56 state:

```cpp
    static constexpr double PERIOD = 864000.0;
```

A day has 86400 seconds, i.e., one zero less. Is this a bug?

Why is the period a compile time constant, when doc/tpgr_format.html states that the input format may override the default?

**Comment by GVeitBatz** [comment]
The unit that leads to 864000 is tenth of a second. So, it is not a bug.

If hard-wired period can be overridden? No it can not. But everybody is free to change the period in the code, or even change the code to make TTFs more flexible.

**Comment by ben-strasser** [comment]
Hi,
>
> The unit that leads to 864000 is tenth of a second. So, it is not a bug.
>
is that documented somewhere?

> If hard-wired period can be overridden? No it can not. But everybody 
> is free to change the period in the code, or even change the code to 
> make TTFs more flexible.
>
The problem is that the graph file format contains a period. If this 
period differs from 864000 then the code just silently does something 
different than the user intended. For example setting it to 86400 in the 
file is a very reasonable choice as seconds combined with floating 
points provide all the accuracy needed. However, the code reads the 
file, all checks pass and when a query goes over the midnight boundary 
then suddenly all traffic seems to be gone.

I know of at least one instance where your code has been used and this 
bug has occurred without the users even noticing that some queries are 
not answered as intended.

Best Regards
Ben

**Comment by GVeitBatz** [comment]
I added some text to README about this and also some code to the read_edges() functions in btch_format.h and tpgr_format.h.

But, honestly, people should do testing, especially if they use some code from the internet.

**Comment by GVeitBatz** [comment]
I also added notes to the html files in subdirectory doc.

**Comment by ben-strasser** [comment]
> But, honestly, people should do testing, especially if they use some code from the internet.

The question is how people who tested it reacted. It is easy to conclude that the code is buggy and not use it. (Whether this conclusion is valid or not does not play a role. It is the case in the eyes of the user and that is what he bases his decision on.) I needed several hours to debug this and I believe that many people do not have the will and time to invest in this type of bug hunting. 

I think that the addition to read_edges is enough to assure that nobody mistakenly runs into this problem. :)
